server:
  port: 80

eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: false
#    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
#    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #单机版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版


#设置feign客户端超时时间(OpenFeign 默认支持ribbon) ，这个不开直接就报错了，哈哈
ribbon:
  #指的是建立连接所用时间,适用于网络状况正常情况下,两端连接所用时间，这里默认为一秒
  ReadTimeout: 5000
  #指的是连接建立后,从服务器获取到可用资源所用时间
  ConnectTimeout: 5000

#开启hystrix
feign:
  hystrix:
    enabled: true


#这里在一个方法里面不得行是因为全局通用的顶住了，自己写的不行  （测试了还是不行，日账得很，应该是这里没有起作用）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000